# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkdup',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.TextField()),
                ('word', models.TextField()),
                ('mean', models.TextField(blank=True, null=True)),
                ('checkdup', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
