# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='word',
            name='start',
        ),
    ]
