# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0002_auto_20161111_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='checkdup',
            new_name='session_num',
        ),
    ]
