# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0003_auto_20161111_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitWord',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
            ],
        ),
    ]
